- name: Install PyMySQL
  ansible.builtin.pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230106111013451800000003.c9fzif5lknrg.eu-west-1.rds.amazonaws.com" 
    login_user: "Kebsadmin"
    login_password: "admin12345"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-20230106111013451800000003.c9fzif5lknrg.eu-west-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "Kebsadmin" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "admin12345" }