- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230106111013451800000003.c9fzif5lknrg.eu-west-1.rds.amazonaws.com"
    login_user: "kebops"
    login_password: "devopspbl19"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20230106111013451800000003.c9fzif5lknrg.eu-west-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "kebops" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "devopspbl19" }

